# Generated by Django 2.2 on 2020-02-12 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Signboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(max_length=100, verbose_name='Summary')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of add')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_bord', to='webapp.Category', verbose_name='Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracker_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_bord', to='webapp.Status', verbose_name='Status')),
            ],
        ),
    ]
